_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 50
                - 53
                - 55
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 49
                - 50
                - 53
                - 55
                - 71
                - 98
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.12.5
            "5": 0.18.2
            "6": 4.35.2
            "8":
                - 5
            "12": 0.18.2
            "13": linux-x86_64
data_processing:
    value:
        augmentation: true
dataset_config:
    value: '{''dataset'': ''speech_dataset'', ''file'': ''src/slam_llm/datasets/speech_dataset.py:get_speech_dataset'', ''train_data_path'': ''/home/liu.ten/demo/SLAM-LLM/examples/asr_librispeech/train_data.jsonl'', ''val_data_path'': ''/home/liu.ten/demo/SLAM-LLM/examples/asr_librispeech/validation_data.jsonl'', ''train_split'': ''train'', ''test_split'': ''validation'', ''prompt'': '''', ''use_data_augmentation'': True, ''data_path'': None, ''max_words'': None, ''max_mel'': None, ''fix_length_audio'': -1, ''inference_mode'': False, ''input_type'': ''raw'', ''mel_size'': 80, ''normalize'': True}'
fsdp_config:
    value: '{''mixed_precision'': True, ''use_fp16'': True, ''sharding_strategy'': ''NO_SHARD'', ''checkpoint_type'': ''SHARDED_STATE_DICT'', ''fsdp_activation_checkpointing'': True, ''fsdp_cpu_offload'': False, ''pure_bf16'': False, ''optimizer'': ''AdamW''}'
log_config:
    value: '{''use_wandb'': True, ''wandb_dir'': ''/home/liu.ten/demo/test_wandb'', ''wandb_entity_name'': ''arno-liut-northeastern-university'', ''wandb_project_name'': ''hate_speech_detection'', ''wandb_exp_name'': ''experiment_1_audio_only'', ''log_file'': ''/home/liu.ten/test.log'', ''log_interval'': 5}'
model_config:
    value: '{''file'': ''examples/asr_librispeech/model/slam_model_asr.py:model_factory'', ''llm_name'': ''TinyLlama-1.1B'', ''llm_path'': ''TinyLlama/TinyLlama-1.1B-Chat-v0.1'', ''llm_type'': ''decoder_only'', ''llm_dim'': 2048, ''feature_pooling'': ''mean'', ''use_dropout'': True, ''dropout_rate'': 0.3, ''input_type'': ''raw'', ''use_contrastive_loss'': False, ''contrastive_temperature'': 0.5, ''encoder_name'': ''wavlm'', ''encoder_ds_rate'': 2, ''encoder_path'': ''/home/liu.ten/demo/SLAM-LLM/src/slam_llm/models/WavLM-Large.pt'', ''encoder_dim'': 1024, ''encoder_projector'': ''linear'', ''encoder_projector_ds_rate'': 5, ''modal'': ''audio'', ''normalize'': True, ''encoder_type'': ''finetune''}'
train_config:
    value: '{''model_name'': ''hate_speech_detection'', ''experiment_type'': ''audio_only'', ''enable_ddp'': True, ''enable_deepspeed'': False, ''enable_fsdp'': False, ''low_cpu_fsdp'': False, ''run_validation'': True, ''batch_size_training'': 8, ''batching_strategy'': ''custom'', ''context_length'': 4096, ''gradient_accumulation_steps'': 1, ''num_epochs'': 400, ''num_workers_dataloader'': 4, ''warmup_steps'': 1000, ''total_steps'': 100000, ''validation_interval'': 100, ''lr'': 0.0001, ''weight_decay'': 0.0, ''gamma'': 0.85, ''seed'': 42, ''use_fp16'': True, ''mixed_precision'': True, ''val_batch_size'': 5, ''use_data_augmentation'': True, ''enable_gradient_checkpointing'': False, ''use_peft'': False, ''peft_config'': {''peft_method'': ''lora'', ''r'': 8, ''lora_alpha'': 32, ''target_modules'': [''q_proj'', ''v_proj''], ''bias'': ''none'', ''task_type'': ''CAUSAL_LM'', ''lora_dropout'': 0.05, ''inference_mode'': False}, ''output_dir'': ''/home/liu.ten/demo/tmp/audio_only-TinyLlama-1.1B-librispeech-linear-steplrwarmupkeep1e-4-wavlm-large-20241114'', ''freeze_layers'': False, ''num_freeze_layers'': 1, ''quantization'': False, ''one_gpu'': False, ''save_model'': True, ''dist_checkpoint_root_folder'': ''PATH/to/save/FSDP/model'', ''dist_checkpoint_folder'': ''fine-tuned'', ''save_optimizer'': False, ''use_fast_kernels'': False, ''run_test'': False, ''run_test_during_validation'': False, ''run_test_during_validation_file'': ''test.wav'', ''run_test_during_validation_prompt'': ''<|ASR|>'', ''freeze_llm'': True, ''freeze_encoder'': True}'
